<?php

declare(strict_types=1);
namespace Webactueel\WordPressConnector\Admin;
use RuntimeException; use Throwable;
final class ElementorJsonExport
{
    private const ACTION='wpconnector_export_elementor_json'; private const POST_TYPES=array('page','post','elementor_library'); private const BUNDLE_FORMAT='wordpressconnector/elementor-site-parts-bundle'; private const BUNDLE_VERSION=1;
    public function register(): void{if(!is_admin()){return;}add_filter('page_row_actions',array($this,'rowActions'),99,2);add_filter('post_row_actions',array($this,'rowActions'),99,2);add_action('admin_post_'.self::ACTION,array($this,'download'));}
    public function rowActions(array $actions,\WP_Post $post): array{if(!$this->supportsPostType((string)$post->post_type)||!current_user_can('edit_post',(int)$post->ID)||!$this->isElementorDocument((int)$post->ID)){return $actions;}if('elementor_library'===(string)$post->post_type&&isset($actions['export-template'])){return $actions;}$actions['wpconnector_export_elementor_json']=sprintf('<a href="%1$s">%2$s</a>',esc_url($this->exportUrl((int)$post->ID,false)),esc_html__('Export Elementor JSON','wordpressconnector'));if(in_array((string)$post->post_type,array('page','post'),true)&&class_exists('ElementorPro\\Modules\\ThemeBuilder\\Module')){$actions['wpconnector_export_elementor_site_parts']=sprintf('<a href="%1$s">%2$s</a>',esc_url($this->exportUrl((int)$post->ID,true)),esc_html__('Export Elementor + Site Parts','wordpressconnector'));}return $actions;}
    public function download(): void
    {
        $postId=isset($_GET['post_id'])?absint(wp_unslash($_GET['post_id'])):0;$includeSiteParts=isset($_GET['include_site_parts'])&&'1'===(string)wp_unslash($_GET['include_site_parts']);if($postId<1){wp_die(esc_html__('Invalid Elementor document.','wordpressconnector'),'',array('response'=>400));}check_admin_referer(self::ACTION.'_'.$postId);$post=get_post($postId);if(!$post instanceof \WP_Post||!$this->supportsPostType((string)$post->post_type)){wp_die(esc_html__('This item cannot be exported as Elementor JSON.','wordpressconnector'),'',array('response'=>400));}if(!current_user_can('edit_post',$postId)){wp_die(esc_html__('You are not allowed to export this Elementor document.','wordpressconnector'),'',array('response'=>403));}if($includeSiteParts&&!in_array((string)$post->post_type,array('page','post'),true)){wp_die(esc_html__('Site-parts export is available only for pages and posts.','wordpressconnector'),'',array('response'=>400));}
        try{$documentPayload=$this->exportPayload($this->document($postId),$post);$payload=$includeSiteParts?$this->bundleWithSiteParts($post,$documentPayload):$documentPayload;$json=wp_json_encode($payload);if(!is_string($json)||''===$json){throw new RuntimeException('WordPress could not encode the Elementor export as JSON.');}}catch(RuntimeException $error){wp_die(esc_html($error->getMessage()),'',array('response'=>400));}catch(Throwable $error){wp_die(esc_html__('The Elementor JSON export could not be completed.','wordpressconnector'),'',array('response'=>500));}
        $slug=''!==(string)$post->post_name?(string)$post->post_name:(string)$post->post_type.'-'.$postId;$filename=sanitize_file_name($slug.($includeSiteParts?'-elementor-with-site-parts.json':'-elementor.json'));nocache_headers();header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename='.$filename);header('Content-Length: '.strlen($json));header('X-Content-Type-Options: nosniff');echo $json;exit;
    }
    private function exportUrl(int $postId,bool $includeSiteParts): string{return wp_nonce_url(add_query_arg(array('action'=>self::ACTION,'post_id'=>$postId,'include_site_parts'=>$includeSiteParts?1:0),admin_url('admin-post.php')),self::ACTION.'_'.$postId);}
    private function exportPayload(object $document,\WP_Post $post): array
    {
        if(!method_exists($document,'get_export_data')){throw new RuntimeException('This Elementor version does not expose document export data.');}$templateData=$document->get_export_data();if(!is_array($templateData)){throw new RuntimeException('Elementor returned invalid export data.');}$content=isset($templateData['content'])&&is_array($templateData['content'])?$templateData['content']:array();$settings=isset($templateData['settings'])&&is_array($templateData['settings'])?$templateData['settings']:array();if(empty($content)){throw new RuntimeException('The Elementor document is empty.');}$content=apply_filters('elementor/template_library/sources/local/export/elements',$content);if(!is_array($content)){throw new RuntimeException('Elementor export filters returned invalid document content.');}$type='elementor_library'===(string)$post->post_type?(string)get_post_meta((int)$post->ID,'_elementor_template_type',true):'';if(''===$type&&method_exists($document,'get_name')){$type=(string)$document->get_name();}if(''===$type){$type='page'===(string)$post->post_type?'wp-page':('post'===(string)$post->post_type?'wp-post':'page');}$payload=array('content'=>$content,'page_settings'=>$settings,'version'=>class_exists('Elementor\\DB')?(string)\Elementor\DB::DB_VERSION:'0.4','title'=>(string)$post->post_title,'type'=>$type);$snapshots=apply_filters('elementor/template_library/export/build_snapshots',array(),$content,(int)$post->ID,$payload);if(is_array($snapshots)){if(!empty($snapshots['global_classes'])){$payload['global_classes']=$snapshots['global_classes'];}if(!empty($snapshots['global_variables'])){$payload['global_variables']=$snapshots['global_variables'];}}return $payload;
    }
    private function bundleWithSiteParts(\WP_Post $post,array $documentPayload): array{$parts=$this->sitePartsForPost($post);return array('format'=>self::BUNDLE_FORMAT,'bundle_version'=>self::BUNDLE_VERSION,'source'=>array('post_id'=>(int)$post->ID,'post_type'=>(string)$post->post_type,'title'=>(string)$post->post_title),'document'=>$documentPayload,'header'=>isset($parts['header']['payload'])?$parts['header']['payload']:null,'footer'=>isset($parts['footer']['payload'])?$parts['footer']['payload']:null,'site_part_meta'=>array('header'=>$this->sitePartMeta($parts['header']??null),'footer'=>$this->sitePartMeta($parts['footer']??null)),'warnings'=>isset($parts['warnings'])&&is_array($parts['warnings'])?$parts['warnings']:array());}
    private function sitePartsForPost(\WP_Post $sourcePost): array
    {
        if(!class_exists('ElementorPro\\Modules\\ThemeBuilder\\Module')){return array('header'=>null,'footer'=>null,'warnings'=>array('Elementor Pro Theme Builder is not active.'));}try{$module=\ElementorPro\Modules\ThemeBuilder\Module::instance();if(!is_object($module)||!method_exists($module,'get_conditions_manager')){return $this->unsupportedSiteParts();}$conditions=$module->get_conditions_manager();if(!is_object($conditions)||!method_exists($conditions,'get_documents_for_location')){return $this->unsupportedSiteParts();}$matches=$this->withSingularQuery($sourcePost,static function()use($conditions):array{return array('header'=>$conditions->get_documents_for_location('header'),'footer'=>$conditions->get_documents_for_location('footer'));});$header=$this->firstSitePart($matches['header']??array(),'header');$footer=$this->firstSitePart($matches['footer']??array(),'footer');$warnings=array();if(null===$header){$warnings[]='No matching Elementor Theme Builder header was found for this document.';}if(null===$footer){$warnings[]='No matching Elementor Theme Builder footer was found for this document.';}return array('header'=>$header,'footer'=>$footer,'warnings'=>$warnings);}catch(Throwable $error){return $this->unsupportedSiteParts('Elementor Pro Theme Builder could not resolve the matching site parts for this document.');}
    }
    private function firstSitePart($matches,string $location): ?array{if(!is_array($matches)||empty($matches)){return null;}foreach($matches as $key=>$document){$templateId=0;$template=null;if(is_object($document)&&method_exists($document,'get_post')){$template=$document->get_post();if($template instanceof \WP_Post){$templateId=(int)$template->ID;}}elseif(is_numeric($key)){$templateId=(int)$key;}elseif(is_numeric($document)){$templateId=(int)$document;}if($templateId<1){continue;}$template=$template instanceof \WP_Post?$template:get_post($templateId);if(!$template instanceof \WP_Post||!current_user_can('edit_post',$templateId)){continue;}$payload=$this->exportPayload($this->document($templateId),$template);if((string)($payload['type']??'')!==$location){continue;}return array('id'=>$templateId,'title'=>(string)$template->post_title,'payload'=>$payload);}return null;}
    private function withSingularQuery(\WP_Post $sourcePost,callable $callback){global $post,$wp_query,$wp_the_query;$previousPost=$post??null;$previousQuery=$wp_query??null;$previousTheQuery=$wp_the_query??null;$args=array('post_type'=>(string)$sourcePost->post_type,'post_status'=>'any','posts_per_page'=>1,'ignore_sticky_posts'=>true,'no_found_rows'=>true);if('page'===(string)$sourcePost->post_type){$args['page_id']=(int)$sourcePost->ID;}else{$args['p']=(int)$sourcePost->ID;}$query=new \WP_Query($args);if(!$query->have_posts()){throw new RuntimeException('The document context could not be prepared for Theme Builder conditions.');}$wp_query=$query;$wp_the_query=$query;$query->the_post();try{return $callback();}finally{$query->reset_postdata();$wp_query=$previousQuery;$wp_the_query=$previousTheQuery;$post=$previousPost;if($previousPost instanceof \WP_Post){setup_postdata($previousPost);}}}
    private function unsupportedSiteParts(string $warning='The active Elementor Pro version does not expose the Theme Builder condition API required for site-parts export.'): array{return array('header'=>null,'footer'=>null,'warnings'=>array($warning));} private function sitePartMeta(?array $part): ?array{return null===$part?null:array('id'=>(int)($part['id']??0),'title'=>(string)($part['title']??''));} private function isElementorDocument(int $postId): bool{if('builder'!==(string)get_post_meta($postId,'_elementor_edit_mode',true)){return false;}try{$this->document($postId);return true;}catch(RuntimeException $error){return false;}} private function document(int $postId): object{if(!class_exists('Elementor\\Plugin')){throw new RuntimeException('Elementor is not active.');}$plugin=\Elementor\Plugin::$instance;$manager=isset($plugin->documents)?$plugin->documents:null;if(!is_object($manager)||!method_exists($manager,'get')){throw new RuntimeException('Elementor document manager is unavailable.');}$document=$manager->get($postId);if(!is_object($document)||!method_exists($document,'get_elements_data')||!method_exists($document,'get_export_data')){throw new RuntimeException('This item is not an exportable Elementor document.');}return $document;} private function supportsPostType(string $postType): bool{return in_array($postType,self::POST_TYPES,true);}
}
