<?php

declare(strict_types=1);
namespace Webactueel\WordPressConnector\Admin;
use RuntimeException; use Throwable; use Webactueel\WordPressConnector\Adapters\ElementorAdapter;
final class ElementorJsonImport
{
    private const ACTION='wpconnector_import_elementor_json'; private const POST_TYPES=array('page','post','elementor_library'); private const MAX_BYTES=5242880;
    public function register(): void{if(!is_admin()){return;}add_filter('page_row_actions',array($this,'rowActions'),99,2);add_filter('post_row_actions',array($this,'rowActions'),99,2);add_action('admin_menu',array($this,'registerImportPages'));add_action('admin_post_'.self::ACTION,array($this,'handleImport'));}
    public function rowActions(array $actions,\WP_Post $post): array{if(!$this->supportsPostType((string)$post->post_type)||!current_user_can('edit_post',(int)$post->ID)){return $actions;}$actions['wpconnector_import_elementor_json']=sprintf('<a href="%1$s">%2$s</a>',esc_url($this->importUrl((string)$post->post_type,(int)$post->ID)),esc_html__('Import Elementor JSON','wordpressconnector'));return $actions;}
    public function registerImportPages(): void{add_submenu_page('edit.php?post_type=page',__('Import Elementor JSON','wordpressconnector'),__('Import Elementor JSON','wordpressconnector'),'edit_pages','wpconnector-import-elementor-page',function():void{$this->renderImportPage('page');});add_submenu_page('edit.php',__('Import Elementor JSON','wordpressconnector'),__('Import Elementor JSON','wordpressconnector'),'edit_posts','wpconnector-import-elementor-post',function():void{$this->renderImportPage('post');});if(post_type_exists('elementor_library')){add_submenu_page('edit.php?post_type=elementor_library',__('Import Elementor JSON','wordpressconnector'),__('Import Elementor JSON','wordpressconnector'),'edit_posts','wpconnector-import-elementor-template',function():void{$this->renderImportPage('elementor_library');});}}
    public function renderImportPage(string $postType): void
    {
        if(!$this->supportsPostType($postType)||!current_user_can($this->capabilityForPostType($postType))){wp_die(esc_html__('You are not allowed to import Elementor JSON here.','wordpressconnector'),'',array('response'=>403));}$selectedId=isset($_GET['post_id'])?absint(wp_unslash($_GET['post_id'])):0;$posts=get_posts(array('post_type'=>$postType,'post_status'=>array('publish','draft','pending','private','future'),'posts_per_page'=>200,'orderby'=>'modified','order'=>'DESC'));
        echo '<div class="wrap"><h1>'.esc_html__('Import Elementor JSON','wordpressconnector').'</h1><p>'.esc_html__('Upload an Elementor JSON document. Choose an existing item to replace only its Elementor structure/settings, or choose Create new to make a new draft. Existing-item writes use Elementor readback and automatic rollback.','wordpressconnector').'</p><form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field(self::ACTION);echo '<input type="hidden" name="action" value="'.esc_attr(self::ACTION).'"><input type="hidden" name="post_type" value="'.esc_attr($postType).'"><table class="form-table" role="presentation"><tbody><tr><th scope="row"><label for="wpconnector-target-post">'.esc_html__('Target','wordpressconnector').'</label></th><td><select id="wpconnector-target-post" name="post_id">';printf('<option value="0"%1$s>%2$s</option>',selected($selectedId,0,false),esc_html__('Create new draft from JSON','wordpressconnector'));foreach($posts as $post){if(!$post instanceof \WP_Post||!current_user_can('edit_post',(int)$post->ID)){continue;}printf('<option value="%1$d"%2$s>%3$s (#%1$d)</option>',(int)$post->ID,selected($selectedId,(int)$post->ID,false),esc_html((string)$post->post_title));}echo '</select></td></tr><tr><th scope="row"><label for="wpconnector-elementor-json">'.esc_html__('Elementor JSON file','wordpressconnector').'</label></th><td><input id="wpconnector-elementor-json" type="file" name="elementor_json" accept="application/json,.json" required><p class="description">'.esc_html__('Accepted fields: content, page_settings (or settings), version, title, type, global_classes and global_variables. Maximum file size: 5 MB.','wordpressconnector').'</p></td></tr></tbody></table>';submit_button(__('Import Elementor JSON','wordpressconnector'));echo '</form></div>';
    }
    public function handleImport(): void
    {
        check_admin_referer(self::ACTION);$postId=isset($_POST['post_id'])?absint(wp_unslash($_POST['post_id'])):0;$postType=isset($_POST['post_type'])?sanitize_key(wp_unslash($_POST['post_type'])):'';if(!$this->supportsPostType($postType)||!current_user_can($this->capabilityForPostType($postType))){wp_die(esc_html__('Invalid Elementor JSON import target.','wordpressconnector'),'',array('response'=>400));}
        try{$payload=$this->uploadedPayload();$data=$payload['content'];$settings=isset($payload['page_settings'])&&is_array($payload['page_settings'])?$payload['page_settings']:(isset($payload['settings'])&&is_array($payload['settings'])?$payload['settings']:array());$adapter=new ElementorAdapter();if($postId>0){$post=get_post($postId);if(!$post instanceof \WP_Post||(string)$post->post_type!==$postType){throw new RuntimeException('The selected import target no longer exists.');}if(!current_user_can('edit_post',$postId)){wp_die(esc_html__('You are not allowed to edit this item.','wordpressconnector'),'',array('response'=>403));}$adapterPayload=array('id'=>$postId,'data'=>$data,'page_settings'=>$settings,'edit_mode'=>'builder');if('elementor_library'===$postType){$adapterPayload['template_type']=$this->templateType($payload);}$adapter->replaceDocument($adapterPayload,array('dry_run'=>false));$resultId=$postId;}else{$adapterPayload=array('post_type'=>$postType,'status'=>'draft','title'=>$this->importTitle($payload,$postType),'data'=>$data,'page_settings'=>$settings,'edit_mode'=>'builder');if('elementor_library'===$postType){$adapterPayload['template_type']=$this->templateType($payload);}$created=$adapter->createDocument($adapterPayload,array('dry_run'=>false));$resultId=isset($created['document']['post_id'])?(int)$created['document']['post_id']:0;if($resultId<1){throw new RuntimeException('Elementor JSON was imported but the new document ID could not be verified.');}}}catch(RuntimeException $error){wp_die(esc_html($error->getMessage()),'',array('response'=>400));}catch(Throwable $error){wp_die(esc_html__('The Elementor JSON import failed.','wordpressconnector'),'',array('response'=>500));}
        wp_safe_redirect(add_query_arg(array('post_type'=>$postType,'wpconnector_elementor_imported'=>1,'post'=>$resultId),admin_url('edit.php')));exit;
    }
    private function uploadedPayload(): array
    {
        if(!isset($_FILES['elementor_json'])||!is_array($_FILES['elementor_json'])){throw new RuntimeException('No Elementor JSON file was uploaded.');}$file=$_FILES['elementor_json'];$error=isset($file['error'])?(int)$file['error']:UPLOAD_ERR_NO_FILE;if(UPLOAD_ERR_OK!==$error){throw new RuntimeException('The Elementor JSON upload failed.');}$size=isset($file['size'])?(int)$file['size']:0;if($size<1||$size>self::MAX_BYTES){throw new RuntimeException('The Elementor JSON file must be between 1 byte and 5 MB.');}$name=isset($file['name'])?sanitize_file_name((string)$file['name']):'';if('json'!==strtolower((string)pathinfo($name,PATHINFO_EXTENSION))){throw new RuntimeException('Choose a .json Elementor export file.');}$tmpName=isset($file['tmp_name'])?(string)$file['tmp_name']:'';if(''===$tmpName||!is_uploaded_file($tmpName)){throw new RuntimeException('The Elementor JSON upload is invalid.');}$raw=file_get_contents($tmpName);if(!is_string($raw)||''===trim($raw)||strlen($raw)>self::MAX_BYTES){throw new RuntimeException('The Elementor JSON file is empty or too large.');}$decoded=json_decode($raw,true);if(!is_array($decoded)||JSON_ERROR_NONE!==json_last_error()){throw new RuntimeException('The uploaded file is not valid JSON.');}if(isset($decoded['format'])&&'wordpressconnector/elementor-site-parts-bundle'===$decoded['format']){if(!isset($decoded['document'])||!is_array($decoded['document'])){throw new RuntimeException('The Elementor site-parts bundle does not contain a document payload.');}$decoded=$decoded['document'];}if(!isset($decoded['content'])||!is_array($decoded['content'])||empty($decoded['content'])){throw new RuntimeException('The JSON is not a non-empty Elementor document export.');}return $decoded;
    }
    private function importTitle(array $payload,string $postType): string{$title=isset($payload['title'])&&is_string($payload['title'])?sanitize_text_field($payload['title']):'';return ''!==$title?$title:('elementor_library'===$postType?'Imported Elementor Template':'Imported Elementor '.ucfirst($postType));} private function templateType(array $payload): string{$type=isset($payload['type'])&&is_string($payload['type'])?sanitize_key($payload['type']):'';return ''!==$type?$type:'page';} private function importUrl(string $postType,int $postId): string{$slug='page'===$postType?'wpconnector-import-elementor-page':('post'===$postType?'wpconnector-import-elementor-post':'wpconnector-import-elementor-template');$base='post'===$postType?admin_url('edit.php'):admin_url('edit.php?post_type='.$postType);return add_query_arg(array('page'=>$slug,'post_id'=>$postId),$base);} private function capabilityForPostType(string $postType): string{return 'page'===$postType?'edit_pages':'edit_posts';} private function supportsPostType(string $postType): bool{return in_array($postType,self::POST_TYPES,true);}
}
